<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="ValidateTitle" tests="1" time="11.733" ignored="0" failures="1" timestamp="29 Jan 2021 15:54:17 GMT" skipped="0" hostname="DESKTOP-A0TKTFQ" errors="0">
  <testcase name="validation" time="11.733" classname="ValidateTitle">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [FEATURED COURSES123] but found [FEATURED COURSES]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [FEATURED COURSES123] but found [FEATURED COURSES]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at ValidateTitle.validation(ValidateTitle.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
]]>
    </failure>
  </testcase> <!-- validation -->
</testsuite> <!-- ValidateTitle -->
